[tools]
1password = "latest"
node = "lts"
"npm:pnpm" = "11"

[tasks.clean]
description = "Limpiar dependencias del proyecto"
run = "rm -rf node_modules"

[tasks.install]
description = "Instalar dependencias del proyecto"
run = "pnpm install"

[tasks.dev]
description = "Arrancar servidor de desarrollo"
run = "pnpm run dev"

[tasks.build]
description = "Compilar para producción"
run = "pnpm run build"

[tasks.preview]
description = "Previsualizar build de producción"
run = "pnpm run preview"

[tasks.check-typing]
description = "Verificar tipos TypeScript"
run = "pnpm run check-typing"

[tasks.test]
description = "Ejecutar tests"
run = "pnpm run test"

[tasks.lint]
description = "Lintear proyecto"
run = "pnpm run lint"
